apiVersion: v2
name: generic
description: A super generic, fully customizable Helm chart for deploying any workload type on Kubernetes
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
  - deployment
  - statefulset
  - daemonset
  - cronjob
  - job
  - kubernetes
  - universal
home: https://github.com/foushua/charts
sources:
  - https://github.com/foushua/charts
maintainers:
  - name: Foushua
    email: foushua@users.noreply.github.com
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: ""
    url: ""
