{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "generic.serviceAccountName" . }}
  namespace: {{ include "generic.namespace" . }}
  labels:
    {{- include "generic.resourceLabels" (dict "context" . "labels" .Values.serviceAccount.labels) | nindent 4 }}
  {{- $annotations := include "generic.resourceAnnotations" (dict "context" . "annotations" .Values.serviceAccount.annotations) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
{{- if not .Values.serviceAccount.automountServiceAccountToken }}
automountServiceAccountToken: false
{{- end }}
{{- with .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
