{{- range $name, $es := .Values.externalSecrets }}
{{- if $es.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "generic.fullname" $ }}-{{ $name }}
  namespace: {{ include "generic.namespace" $ }}
  labels:
    {{- include "generic.resourceLabels" (dict "context" $ "labels" $es.labels) | nindent 4 }}
  {{- $annotations := include "generic.resourceAnnotations" (dict "context" $ "annotations" $es.annotations) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if $es.refreshInterval }}
  refreshInterval: {{ $es.refreshInterval }}
  {{- end }}
  secretStoreRef:
    name: {{ $es.secretStoreRef.name }}
    kind: {{ $es.secretStoreRef.kind | default "SecretStore" }}
  {{- with $es.target }}
  target:
    name: {{ .name | default (printf "%s-%s" (include "generic.fullname" $) $name) }}
    {{- if .creationPolicy }}
    creationPolicy: {{ .creationPolicy }}
    {{- end }}
    {{- if .deletionPolicy }}
    deletionPolicy: {{ .deletionPolicy }}
    {{- end }}
    {{- with .template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- with $es.data }}
  data:
    {{- range . }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
        {{- if .remoteRef.version }}
        version: {{ .remoteRef.version | quote }}
        {{- end }}
        {{- if .remoteRef.conversionStrategy }}
        conversionStrategy: {{ .remoteRef.conversionStrategy }}
        {{- end }}
        {{- if .remoteRef.decodingStrategy }}
        decodingStrategy: {{ .remoteRef.decodingStrategy }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- with $es.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
