{{- if and .Values.pdb.enabled (or (eq .Values.workload.type "deployment") (eq .Values.workload.type "statefulset")) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "generic.fullname" . }}
  namespace: {{ include "generic.namespace" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  {{- $annotations := include "generic.resourceAnnotations" (dict "context" . "annotations" dict) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" . | nindent 6 }}
{{- end }}
