{{- range $name, $secret := .Values.secrets }}
{{- if $secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flex.fullname" $ }}-{{ $name }}
  namespace: {{ include "flex.namespace" $ }}
  labels:
    {{- include "flex.resourceLabels" (dict "context" $ "labels" $secret.labels) | nindent 4 }}
  {{- $annotations := include "flex.resourceAnnotations" (dict "context" $ "annotations" $secret.annotations) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
type: {{ $secret.type | default "Opaque" }}
{{- with $secret.data }}
data:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- with $secret.stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
{{- end }}
{{- end }}
